name: build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build images
        run: |
          docker buildx bake \
            --set '*.cache-from=type=registry,ref=ghcr.io/bzub/images:buildcache' \
            --set '*.cache-to=type=registry,ref=ghcr.io/bzub/images:buildcache,mode=max'
            # --set '*.cache-from=type=gha,scope=main-cache' \
            # --set '*.cache-to=type=gha,scope=main-cache,mode=max'
